enabled_layouts tall, vertical

font_family Hasklug Nerd Font Mono
font_size 13
disable_ligatures never

tab_bar_style slant
tab_bar_separator "|"

hide_window_decorations yes

background_opacity 0.8

active_tab_foreground   #fff
active_tab_background   #000
inactive_tab_foreground #666
inactive_tab_background #000
