enabled_layouts tall, vertical

font_family Hasklug Nerd Font Mono
font_size 13
disable_ligatures never

tab_bar_style separator
tab_bar_separator "|"

active_tab_foreground   #fff
active_tab_background   #000
inactive_tab_foreground #444
inactive_tab_background #000
